swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /accounts:
    get:
      tags:
        - Transactions Module
      summary: Retrieve all the bank accounts in the Profile page
      description: API for fetching all the bank accounts
      responses:
        '200':
          description: Bank accounts retrieved successfully
          schema:
            $ref: '#/definitions/Accounts'
        '400':
          description: Unauthorized access
        '500':
          description: Internal Server Error
  /accounts/{currentAccount}/transactions:
    get:
      tags:
        - Transactions Module
      summary: Retrieve all the current month's transactions of the account
      description: API for retrieving specific account's transactions
      parameters:
        - in: path
          name: currentAccount
          type: string
          description: ID of the current account
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Unauthorized access
        '500':
          description: Internal Server Error
  /accounts/{currentAccount}/transactions/{transactionId}:
    put:
      tags:
        - Transactions Module
      summary: Update one transaction's details
      description: API for Login
      parameters:
        - in: path
          name: currentAccount
          type: string
          description: ID of the current account
          required: true
        - in: path
          name: transactionId
          type: string
          description: ID of the current transaction
          required: true
        - in: body
          name: body
          description: ID of the current transaction
          required: true
          schema:
            $ref: '#/definitions/UpdateTransactions'
      responses:
        '200':
          description: Successfully updated current transaction's details 
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Unauthorized access
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Accounts:
    properties:
      accountType:
        type: string
      accountCurrency:
        type: string
      accountAmount:
        type: number
      accountDescription:
        type: string
      accountNumber:
        type: string
      accountId:
        type: string
  Transactions:
    type: array
    items:
      type: object
      properties:
        transactionId:
          type: string
        date:
          type: string
          format: date-time
        description:
          type: string
        amount:
          type: integer
        balance:
          type: integer
        category:
          type: string
        notes:
          type: string
  UpdateTransactions:
    properties:
      category:
        type: string
      notes:
        type: string